/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VestiMedijiRouteImport } from './routes/vesti-mediji'
import { Route as UsloviKoriscenjaRouteImport } from './routes/uslovi-koriscenja'
import { Route as UplateIsplateRouteImport } from './routes/uplate-isplate'
import { Route as SvetRegulativeRouteImport } from './routes/svet-regulative'
import { Route as SveOIgricamaRouteImport } from './routes/sve-o-igricama'
import { Route as RegistracijaVerifikacijaRouteImport } from './routes/registracija-verifikacija'
import { Route as RecStrucnjakaRouteImport } from './routes/rec-strucnjaka'
import { Route as PostaviPitanjeRouteImport } from './routes/postavi-pitanje'
import { Route as PomocRouteImport } from './routes/pomoc'
import { Route as PolitikaPrivatnostiRouteImport } from './routes/politika-privatnosti'
import { Route as OdgovornaIgraRouteImport } from './routes/odgovorna-igra'
import { Route as ONamaRouteImport } from './routes/o-nama'
import { Route as KolaciciRouteImport } from './routes/kolacici'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as BonusUsloviRouteImport } from './routes/bonus-uslovi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VestiMedijiSlugRouteImport } from './routes/vesti-mediji.$slug'
import { Route as UplateIsplateSlugRouteImport } from './routes/uplate-isplate_.$slug'
import { Route as SvetRegulativeSlugRouteImport } from './routes/svet-regulative_.$slug'
import { Route as SveOIgricamaSlugRouteImport } from './routes/sve-o-igricama_.$slug'
import { Route as RegistracijaVerifikacijaSlugRouteImport } from './routes/registracija-verifikacija_.$slug'
import { Route as RecStrucnjakaSlugRouteImport } from './routes/rec-strucnjaka.$slug'
import { Route as OdgovornaIgraSlugRouteImport } from './routes/odgovorna-igra_.$slug'
import { Route as BonusUsloviSlugRouteImport } from './routes/bonus-uslovi_.$slug'

const VestiMedijiRoute = VestiMedijiRouteImport.update({
  id: '/vesti-mediji',
  path: '/vesti-mediji',
  getParentRoute: () => rootRouteImport,
} as any)
const UsloviKoriscenjaRoute = UsloviKoriscenjaRouteImport.update({
  id: '/uslovi-koriscenja',
  path: '/uslovi-koriscenja',
  getParentRoute: () => rootRouteImport,
} as any)
const UplateIsplateRoute = UplateIsplateRouteImport.update({
  id: '/uplate-isplate',
  path: '/uplate-isplate',
  getParentRoute: () => rootRouteImport,
} as any)
const SvetRegulativeRoute = SvetRegulativeRouteImport.update({
  id: '/svet-regulative',
  path: '/svet-regulative',
  getParentRoute: () => rootRouteImport,
} as any)
const SveOIgricamaRoute = SveOIgricamaRouteImport.update({
  id: '/sve-o-igricama',
  path: '/sve-o-igricama',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistracijaVerifikacijaRoute =
  RegistracijaVerifikacijaRouteImport.update({
    id: '/registracija-verifikacija',
    path: '/registracija-verifikacija',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecStrucnjakaRoute = RecStrucnjakaRouteImport.update({
  id: '/rec-strucnjaka',
  path: '/rec-strucnjaka',
  getParentRoute: () => rootRouteImport,
} as any)
const PostaviPitanjeRoute = PostaviPitanjeRouteImport.update({
  id: '/postavi-pitanje',
  path: '/postavi-pitanje',
  getParentRoute: () => rootRouteImport,
} as any)
const PomocRoute = PomocRouteImport.update({
  id: '/pomoc',
  path: '/pomoc',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaPrivatnostiRoute = PolitikaPrivatnostiRouteImport.update({
  id: '/politika-privatnosti',
  path: '/politika-privatnosti',
  getParentRoute: () => rootRouteImport,
} as any)
const OdgovornaIgraRoute = OdgovornaIgraRouteImport.update({
  id: '/odgovorna-igra',
  path: '/odgovorna-igra',
  getParentRoute: () => rootRouteImport,
} as any)
const ONamaRoute = ONamaRouteImport.update({
  id: '/o-nama',
  path: '/o-nama',
  getParentRoute: () => rootRouteImport,
} as any)
const KolaciciRoute = KolaciciRouteImport.update({
  id: '/kolacici',
  path: '/kolacici',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusUsloviRoute = BonusUsloviRouteImport.update({
  id: '/bonus-uslovi',
  path: '/bonus-uslovi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VestiMedijiSlugRoute = VestiMedijiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VestiMedijiRoute,
} as any)
const UplateIsplateSlugRoute = UplateIsplateSlugRouteImport.update({
  id: '/uplate-isplate_/$slug',
  path: '/uplate-isplate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SvetRegulativeSlugRoute = SvetRegulativeSlugRouteImport.update({
  id: '/svet-regulative_/$slug',
  path: '/svet-regulative/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SveOIgricamaSlugRoute = SveOIgricamaSlugRouteImport.update({
  id: '/sve-o-igricama_/$slug',
  path: '/sve-o-igricama/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistracijaVerifikacijaSlugRoute =
  RegistracijaVerifikacijaSlugRouteImport.update({
    id: '/registracija-verifikacija_/$slug',
    path: '/registracija-verifikacija/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecStrucnjakaSlugRoute = RecStrucnjakaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RecStrucnjakaRoute,
} as any)
const OdgovornaIgraSlugRoute = OdgovornaIgraSlugRouteImport.update({
  id: '/odgovorna-igra_/$slug',
  path: '/odgovorna-igra/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusUsloviSlugRoute = BonusUsloviSlugRouteImport.update({
  id: '/bonus-uslovi_/$slug',
  path: '/bonus-uslovi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonus-uslovi': typeof BonusUsloviRoute
  '/disclaimer': typeof DisclaimerRoute
  '/kolacici': typeof KolaciciRoute
  '/o-nama': typeof ONamaRoute
  '/odgovorna-igra': typeof OdgovornaIgraRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/pomoc': typeof PomocRoute
  '/postavi-pitanje': typeof PostaviPitanjeRoute
  '/rec-strucnjaka': typeof RecStrucnjakaRouteWithChildren
  '/registracija-verifikacija': typeof RegistracijaVerifikacijaRoute
  '/sve-o-igricama': typeof SveOIgricamaRoute
  '/svet-regulative': typeof SvetRegulativeRoute
  '/uplate-isplate': typeof UplateIsplateRoute
  '/uslovi-koriscenja': typeof UsloviKoriscenjaRoute
  '/vesti-mediji': typeof VestiMedijiRouteWithChildren
  '/bonus-uslovi/$slug': typeof BonusUsloviSlugRoute
  '/odgovorna-igra/$slug': typeof OdgovornaIgraSlugRoute
  '/rec-strucnjaka/$slug': typeof RecStrucnjakaSlugRoute
  '/registracija-verifikacija/$slug': typeof RegistracijaVerifikacijaSlugRoute
  '/sve-o-igricama/$slug': typeof SveOIgricamaSlugRoute
  '/svet-regulative/$slug': typeof SvetRegulativeSlugRoute
  '/uplate-isplate/$slug': typeof UplateIsplateSlugRoute
  '/vesti-mediji/$slug': typeof VestiMedijiSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bonus-uslovi': typeof BonusUsloviRoute
  '/disclaimer': typeof DisclaimerRoute
  '/kolacici': typeof KolaciciRoute
  '/o-nama': typeof ONamaRoute
  '/odgovorna-igra': typeof OdgovornaIgraRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/pomoc': typeof PomocRoute
  '/postavi-pitanje': typeof PostaviPitanjeRoute
  '/rec-strucnjaka': typeof RecStrucnjakaRouteWithChildren
  '/registracija-verifikacija': typeof RegistracijaVerifikacijaRoute
  '/sve-o-igricama': typeof SveOIgricamaRoute
  '/svet-regulative': typeof SvetRegulativeRoute
  '/uplate-isplate': typeof UplateIsplateRoute
  '/uslovi-koriscenja': typeof UsloviKoriscenjaRoute
  '/vesti-mediji': typeof VestiMedijiRouteWithChildren
  '/bonus-uslovi/$slug': typeof BonusUsloviSlugRoute
  '/odgovorna-igra/$slug': typeof OdgovornaIgraSlugRoute
  '/rec-strucnjaka/$slug': typeof RecStrucnjakaSlugRoute
  '/registracija-verifikacija/$slug': typeof RegistracijaVerifikacijaSlugRoute
  '/sve-o-igricama/$slug': typeof SveOIgricamaSlugRoute
  '/svet-regulative/$slug': typeof SvetRegulativeSlugRoute
  '/uplate-isplate/$slug': typeof UplateIsplateSlugRoute
  '/vesti-mediji/$slug': typeof VestiMedijiSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bonus-uslovi': typeof BonusUsloviRoute
  '/disclaimer': typeof DisclaimerRoute
  '/kolacici': typeof KolaciciRoute
  '/o-nama': typeof ONamaRoute
  '/odgovorna-igra': typeof OdgovornaIgraRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/pomoc': typeof PomocRoute
  '/postavi-pitanje': typeof PostaviPitanjeRoute
  '/rec-strucnjaka': typeof RecStrucnjakaRouteWithChildren
  '/registracija-verifikacija': typeof RegistracijaVerifikacijaRoute
  '/sve-o-igricama': typeof SveOIgricamaRoute
  '/svet-regulative': typeof SvetRegulativeRoute
  '/uplate-isplate': typeof UplateIsplateRoute
  '/uslovi-koriscenja': typeof UsloviKoriscenjaRoute
  '/vesti-mediji': typeof VestiMedijiRouteWithChildren
  '/bonus-uslovi_/$slug': typeof BonusUsloviSlugRoute
  '/odgovorna-igra_/$slug': typeof OdgovornaIgraSlugRoute
  '/rec-strucnjaka/$slug': typeof RecStrucnjakaSlugRoute
  '/registracija-verifikacija_/$slug': typeof RegistracijaVerifikacijaSlugRoute
  '/sve-o-igricama_/$slug': typeof SveOIgricamaSlugRoute
  '/svet-regulative_/$slug': typeof SvetRegulativeSlugRoute
  '/uplate-isplate_/$slug': typeof UplateIsplateSlugRoute
  '/vesti-mediji/$slug': typeof VestiMedijiSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bonus-uslovi'
    | '/disclaimer'
    | '/kolacici'
    | '/o-nama'
    | '/odgovorna-igra'
    | '/politika-privatnosti'
    | '/pomoc'
    | '/postavi-pitanje'
    | '/rec-strucnjaka'
    | '/registracija-verifikacija'
    | '/sve-o-igricama'
    | '/svet-regulative'
    | '/uplate-isplate'
    | '/uslovi-koriscenja'
    | '/vesti-mediji'
    | '/bonus-uslovi/$slug'
    | '/odgovorna-igra/$slug'
    | '/rec-strucnjaka/$slug'
    | '/registracija-verifikacija/$slug'
    | '/sve-o-igricama/$slug'
    | '/svet-regulative/$slug'
    | '/uplate-isplate/$slug'
    | '/vesti-mediji/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bonus-uslovi'
    | '/disclaimer'
    | '/kolacici'
    | '/o-nama'
    | '/odgovorna-igra'
    | '/politika-privatnosti'
    | '/pomoc'
    | '/postavi-pitanje'
    | '/rec-strucnjaka'
    | '/registracija-verifikacija'
    | '/sve-o-igricama'
    | '/svet-regulative'
    | '/uplate-isplate'
    | '/uslovi-koriscenja'
    | '/vesti-mediji'
    | '/bonus-uslovi/$slug'
    | '/odgovorna-igra/$slug'
    | '/rec-strucnjaka/$slug'
    | '/registracija-verifikacija/$slug'
    | '/sve-o-igricama/$slug'
    | '/svet-regulative/$slug'
    | '/uplate-isplate/$slug'
    | '/vesti-mediji/$slug'
  id:
    | '__root__'
    | '/'
    | '/bonus-uslovi'
    | '/disclaimer'
    | '/kolacici'
    | '/o-nama'
    | '/odgovorna-igra'
    | '/politika-privatnosti'
    | '/pomoc'
    | '/postavi-pitanje'
    | '/rec-strucnjaka'
    | '/registracija-verifikacija'
    | '/sve-o-igricama'
    | '/svet-regulative'
    | '/uplate-isplate'
    | '/uslovi-koriscenja'
    | '/vesti-mediji'
    | '/bonus-uslovi_/$slug'
    | '/odgovorna-igra_/$slug'
    | '/rec-strucnjaka/$slug'
    | '/registracija-verifikacija_/$slug'
    | '/sve-o-igricama_/$slug'
    | '/svet-regulative_/$slug'
    | '/uplate-isplate_/$slug'
    | '/vesti-mediji/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BonusUsloviRoute: typeof BonusUsloviRoute
  DisclaimerRoute: typeof DisclaimerRoute
  KolaciciRoute: typeof KolaciciRoute
  ONamaRoute: typeof ONamaRoute
  OdgovornaIgraRoute: typeof OdgovornaIgraRoute
  PolitikaPrivatnostiRoute: typeof PolitikaPrivatnostiRoute
  PomocRoute: typeof PomocRoute
  PostaviPitanjeRoute: typeof PostaviPitanjeRoute
  RecStrucnjakaRoute: typeof RecStrucnjakaRouteWithChildren
  RegistracijaVerifikacijaRoute: typeof RegistracijaVerifikacijaRoute
  SveOIgricamaRoute: typeof SveOIgricamaRoute
  SvetRegulativeRoute: typeof SvetRegulativeRoute
  UplateIsplateRoute: typeof UplateIsplateRoute
  UsloviKoriscenjaRoute: typeof UsloviKoriscenjaRoute
  VestiMedijiRoute: typeof VestiMedijiRouteWithChildren
  BonusUsloviSlugRoute: typeof BonusUsloviSlugRoute
  OdgovornaIgraSlugRoute: typeof OdgovornaIgraSlugRoute
  RegistracijaVerifikacijaSlugRoute: typeof RegistracijaVerifikacijaSlugRoute
  SveOIgricamaSlugRoute: typeof SveOIgricamaSlugRoute
  SvetRegulativeSlugRoute: typeof SvetRegulativeSlugRoute
  UplateIsplateSlugRoute: typeof UplateIsplateSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vesti-mediji': {
      id: '/vesti-mediji'
      path: '/vesti-mediji'
      fullPath: '/vesti-mediji'
      preLoaderRoute: typeof VestiMedijiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslovi-koriscenja': {
      id: '/uslovi-koriscenja'
      path: '/uslovi-koriscenja'
      fullPath: '/uslovi-koriscenja'
      preLoaderRoute: typeof UsloviKoriscenjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uplate-isplate': {
      id: '/uplate-isplate'
      path: '/uplate-isplate'
      fullPath: '/uplate-isplate'
      preLoaderRoute: typeof UplateIsplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/svet-regulative': {
      id: '/svet-regulative'
      path: '/svet-regulative'
      fullPath: '/svet-regulative'
      preLoaderRoute: typeof SvetRegulativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sve-o-igricama': {
      id: '/sve-o-igricama'
      path: '/sve-o-igricama'
      fullPath: '/sve-o-igricama'
      preLoaderRoute: typeof SveOIgricamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registracija-verifikacija': {
      id: '/registracija-verifikacija'
      path: '/registracija-verifikacija'
      fullPath: '/registracija-verifikacija'
      preLoaderRoute: typeof RegistracijaVerifikacijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rec-strucnjaka': {
      id: '/rec-strucnjaka'
      path: '/rec-strucnjaka'
      fullPath: '/rec-strucnjaka'
      preLoaderRoute: typeof RecStrucnjakaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postavi-pitanje': {
      id: '/postavi-pitanje'
      path: '/postavi-pitanje'
      fullPath: '/postavi-pitanje'
      preLoaderRoute: typeof PostaviPitanjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomoc': {
      id: '/pomoc'
      path: '/pomoc'
      fullPath: '/pomoc'
      preLoaderRoute: typeof PomocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-privatnosti': {
      id: '/politika-privatnosti'
      path: '/politika-privatnosti'
      fullPath: '/politika-privatnosti'
      preLoaderRoute: typeof PolitikaPrivatnostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odgovorna-igra': {
      id: '/odgovorna-igra'
      path: '/odgovorna-igra'
      fullPath: '/odgovorna-igra'
      preLoaderRoute: typeof OdgovornaIgraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nama': {
      id: '/o-nama'
      path: '/o-nama'
      fullPath: '/o-nama'
      preLoaderRoute: typeof ONamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kolacici': {
      id: '/kolacici'
      path: '/kolacici'
      fullPath: '/kolacici'
      preLoaderRoute: typeof KolaciciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus-uslovi': {
      id: '/bonus-uslovi'
      path: '/bonus-uslovi'
      fullPath: '/bonus-uslovi'
      preLoaderRoute: typeof BonusUsloviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vesti-mediji/$slug': {
      id: '/vesti-mediji/$slug'
      path: '/$slug'
      fullPath: '/vesti-mediji/$slug'
      preLoaderRoute: typeof VestiMedijiSlugRouteImport
      parentRoute: typeof VestiMedijiRoute
    }
    '/uplate-isplate_/$slug': {
      id: '/uplate-isplate_/$slug'
      path: '/uplate-isplate/$slug'
      fullPath: '/uplate-isplate/$slug'
      preLoaderRoute: typeof UplateIsplateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/svet-regulative_/$slug': {
      id: '/svet-regulative_/$slug'
      path: '/svet-regulative/$slug'
      fullPath: '/svet-regulative/$slug'
      preLoaderRoute: typeof SvetRegulativeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sve-o-igricama_/$slug': {
      id: '/sve-o-igricama_/$slug'
      path: '/sve-o-igricama/$slug'
      fullPath: '/sve-o-igricama/$slug'
      preLoaderRoute: typeof SveOIgricamaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registracija-verifikacija_/$slug': {
      id: '/registracija-verifikacija_/$slug'
      path: '/registracija-verifikacija/$slug'
      fullPath: '/registracija-verifikacija/$slug'
      preLoaderRoute: typeof RegistracijaVerifikacijaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rec-strucnjaka/$slug': {
      id: '/rec-strucnjaka/$slug'
      path: '/$slug'
      fullPath: '/rec-strucnjaka/$slug'
      preLoaderRoute: typeof RecStrucnjakaSlugRouteImport
      parentRoute: typeof RecStrucnjakaRoute
    }
    '/odgovorna-igra_/$slug': {
      id: '/odgovorna-igra_/$slug'
      path: '/odgovorna-igra/$slug'
      fullPath: '/odgovorna-igra/$slug'
      preLoaderRoute: typeof OdgovornaIgraSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus-uslovi_/$slug': {
      id: '/bonus-uslovi_/$slug'
      path: '/bonus-uslovi/$slug'
      fullPath: '/bonus-uslovi/$slug'
      preLoaderRoute: typeof BonusUsloviSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RecStrucnjakaRouteChildren {
  RecStrucnjakaSlugRoute: typeof RecStrucnjakaSlugRoute
}

const RecStrucnjakaRouteChildren: RecStrucnjakaRouteChildren = {
  RecStrucnjakaSlugRoute: RecStrucnjakaSlugRoute,
}

const RecStrucnjakaRouteWithChildren = RecStrucnjakaRoute._addFileChildren(
  RecStrucnjakaRouteChildren,
)

interface VestiMedijiRouteChildren {
  VestiMedijiSlugRoute: typeof VestiMedijiSlugRoute
}

const VestiMedijiRouteChildren: VestiMedijiRouteChildren = {
  VestiMedijiSlugRoute: VestiMedijiSlugRoute,
}

const VestiMedijiRouteWithChildren = VestiMedijiRoute._addFileChildren(
  VestiMedijiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BonusUsloviRoute: BonusUsloviRoute,
  DisclaimerRoute: DisclaimerRoute,
  KolaciciRoute: KolaciciRoute,
  ONamaRoute: ONamaRoute,
  OdgovornaIgraRoute: OdgovornaIgraRoute,
  PolitikaPrivatnostiRoute: PolitikaPrivatnostiRoute,
  PomocRoute: PomocRoute,
  PostaviPitanjeRoute: PostaviPitanjeRoute,
  RecStrucnjakaRoute: RecStrucnjakaRouteWithChildren,
  RegistracijaVerifikacijaRoute: RegistracijaVerifikacijaRoute,
  SveOIgricamaRoute: SveOIgricamaRoute,
  SvetRegulativeRoute: SvetRegulativeRoute,
  UplateIsplateRoute: UplateIsplateRoute,
  UsloviKoriscenjaRoute: UsloviKoriscenjaRoute,
  VestiMedijiRoute: VestiMedijiRouteWithChildren,
  BonusUsloviSlugRoute: BonusUsloviSlugRoute,
  OdgovornaIgraSlugRoute: OdgovornaIgraSlugRoute,
  RegistracijaVerifikacijaSlugRoute: RegistracijaVerifikacijaSlugRoute,
  SveOIgricamaSlugRoute: SveOIgricamaSlugRoute,
  SvetRegulativeSlugRoute: SvetRegulativeSlugRoute,
  UplateIsplateSlugRoute: UplateIsplateSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
